project:
  type: website
  output-dir: docs

website:
  title: "Carpentries-Israel"
  favicon: img/carpentries_il_logo.jpeg
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

